### ISSUE TITLE
bfe - get upstream updates from lcnetdev

### ISSUE THREAD

**Issue by ndushay** [LD4P/bfe#15]
See https://help.github.com/articles/syncing-a-fork/

**Comment by ndushay** [comment]
Awesome.  I *think* this means upstream still has build artifacts checked in?

```
CONFLICT (modify/delete): builds/bfe.min.js deleted in HEAD and modified in lcnetdev/master. Version lcnetdev/master of builds/bfe.min.js left in tree.
CONFLICT (modify/delete): builds/bfe.min.css deleted in HEAD and modified in lcnetdev/master. Version lcnetdev/master of builds/bfe.min.css left in tree.
CONFLICT (modify/delete): builds/bfe.js deleted in HEAD and modified in lcnetdev/master. Version lcnetdev/master of builds/bfe.js left in tree.
CONFLICT (modify/delete): builds/bfe.css deleted in HEAD and modified in lcnetdev/master. Version lcnetdev/master of builds/bfe.css left in tree.
```

**Comment by jermnelson** [comment]
So from the LD4P/QA meeting, most of the IndexData work in `bfe` has been merged into master, authentication and authorization still remaining.

**Comment by jermnelson** [comment]
@ndushay , I added the `builds` directory to the .gitignore for this fork and removed the existing builds/*.js files from our report with `git rm ...` as part of an PR [#12](https://github.com/LD4P/bfe/pull/12)

**Comment by ndushay** [comment]
currently working in branch `naomi-restart`.  It seems like `src/bfe.js` is now what it should be -- I did a diff with `build/bfe.js` and the diff was what we would expect:  ace stuff and the other js in the `src` dir.

will close this ticket when we make decisions:
- [ ] which github repo gets our development?  (here or sinopia_editor)
- [ ] is the work in my branch a good starting point?  If so, and this github repo is the one we'll use, force merge my branch into master (via PR).  If not, let's make a separate ticket for a good starting point and get that done.

**Comment by ndushay** [comment]
We decided to use sinopia_editor github repo as the new true home.  As Christina pointed out, the PRs in a forked repo on github become fraught with peril as they default to a PR on the repo you forked from.

I have already pushed up the code in my `naomi-restart` branch on LD4P/bfe.js as the new master branch in origin for sinopia_editor (so it has all the lcnetdev history).

**Comment by ndushay** [comment]
I'll close this after:
- [x] issues  from LD4P/bfe copied to the sinopia_editor
- [x] waffle board fixed up for new issues (in right columns / positions)
- [x] LD4P/bfe renamed LD4P/bfe-defunct
